# Generated by Django 2.1.4 on 2019-04-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181230_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='has_fb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='reactions',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='shares',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
