# Generated by Django 3.1.3 on 2021-01-18 20:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190515_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='paragraphs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
