# Generated by Django 3.2.8 on 2021-12-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_pluses_article_ips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='article',
            name='has_fb',
        ),
        migrations.RemoveField(
            model_name='article',
            name='reactions',
        ),
        migrations.RemoveField(
            model_name='article',
            name='shares',
        ),
    ]
